services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - modulo4_net

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - modulo4_net

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - modulo4_net

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker3
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - modulo4_net

  create-topics:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    entrypoint: ["/bin/sh", "-c"]
    command: |
      sleep 15 && \
      kafka-topics --bootstrap-server broker1:9092,broker2:9092,broker3:9092 \
        --create --topic my-topic --if-not-exists --partitions 5 --replication-factor 3 || true
    networks:
      - modulo4_net
    restart: "no"

  producer:
    build:
      context: ./producer-kafka
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      TOPIC_NAME: my-topic
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - modulo4_net

  consumer-kafka-1:
    build:
      context: ./consumer-kafka-1
      dockerfile: Dockerfile
    container_name: consumer-kafka-1
    ports:
      - "8081:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      TOPIC_NAME: my-topic
      CONSUMER_GROUP: consumer-group-1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - modulo4_net

  consumer-kafka-2:
    build:
      context: ./consumer-kafka-2
      dockerfile: Dockerfile
    container_name: consumer-kafka-2
    ports:
      - "8082:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      TOPIC_NAME: my-topic
      CONSUMER_GROUP: consumer-group-2
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - modulo4_net

networks:
  modulo4_net:
    driver: bridge
